[package]
name = "some-example-crate"
version = "0.1.0"
authors = ["Rust Coder <name@example.com>"]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/example/example-repo"
rust-version = "1.74"
description = "An example Rust app"

[dependencies]
ahash = "0.8"
clap = { version = "4.5.23", features = ["derive"] }
clap-verbosity-flag = "3.0.0"
config = "0.14.1"
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }

[dependencies.sqlx]
version = "0.8.2"
default-features = false
features = ["any", "chrono", "macros", "migrate", "postgres", "runtime-tokio-rustls", "uuid"]

[dev-dependencies]
assert_fs = "1.1.2"
trycmd = "0.15.8"
